apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kerberos.name" . }}-kdc-config
  labels:
    app: {{ template "kerberos.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: kdc
data:
  kdc.conf: |-
    [kdcdefaults]
     kdc_ports = {{ .Values.kdc.udp.port }}
     kdc_tcp_ports = {{ .Values.kdc.tcp.port }}
     restrict_anonymous_to_tgt = {{ .Values.kdc.restrict_anonymous }}
     spake_preauth_kdc_challenge = {{ .Values.kdc.preauth_challenge }}

    [realms]
{{- range $key, $value := .Values.realms }}
     {{ $key | upper }} = {
      master_key_type = {{ $value.master_key_type }}
      max_life = {{ $value.max_life }}
      max_renewable_life = {{ $value.max_renew_life }}
      acl_file = {{ $value.acl_file }}
      dict_file = /usr/share/dict/cracklib-words
{{- if $value.kdc_extra_configs }}
{{ $value.kdc_extra_configs | trim | indent 6 }}
{{- end }}
     }
{{- end }}

  kadm5.acl: |-
{{- range $key, $value := .Values.realms }}
{{- range $acl := $value.acls }}
    {{ $acl.princ }}@{{ $key | upper }}   {{ $acl.perms }}   {{ if $acl.target }}{{ $acl.target }}{{ end }}   {{ if $acl.restrictions }}{{ $acl.restrictions }}{{ end }}
{{- end }}
{{ end }}
