apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "kerberos.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "kerberos.name" . }}
type: Opaque
data:
  {{- if .Values.kdc.password }}
  master-password: {{ .Values.kdc.password | b64enc | quote }}
  {{- else }}
  master-password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}