apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kerberos.name" . }}-krb5-config
  labels:
    app: {{ template "kerberos.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: krb5
data:
  krb5.conf: |-
    [logging]
     default = CONSOLE
     kdc = CONSOLE
     admin_server = CONSOLE

    [libdefaults]
     default_realm = {{ .Values.krb5.default_realm | upper }}
     dns_lookup_realm = {{ .Values.krb5.lookup_realm }}
     dns_lookup_kdc = {{ .Values.krb5.lookup_kdc }}
     rdns = {{ .Values.krb5.rdns }}
     ticket_lifetime = {{ .Values.krb5.ticket_lifetime }}
     forwardable = {{ .Values.krb5.forwardable }}
     udp_preference_limit = 0
     default_ccache_name = {{ .Values.krb5.default_ccache_path }}/{{ .Values.krb5.default_ccache_file }}
     permitted_enctypes = {{ .Values.krb5.enc_types }}

    [realms]
{{- range $key, $value := .Values.realms }}
     {{ $key | upper }} = {
      kdc = {{ template "kerberos.name" $ }}-kdc.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.kdc.udp.port }}
      kdc = {{ template "kerberos.name" $ }}-kdc-1.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.kdc.udp.port }}
      master_kdc = {{ template "kerberos.name" $ }}-kdc.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.kdc.udp.port }}
      admin_server = {{ template "kerberos.name" $ }}-kadmin.{{ $.Release.Namespace }}.svc.cluster.local:749
      default_domain = cluster.local
{{- if $value.krb5_extra_configs }}
{{ $value.krb5_extra_configs | trim | indent 6 }}
{{- end}}
     }
{{- end }}

    [domain_realm]
{{- range $key, $value := .Values.realms }}
     .cluster.local = {{ $key | upper }}
     {{ $key }} = {{ $key | upper }}
{{- if $value.extra_domains }}
{{- range $item := $value.extra_domains }}
     {{ $item }} = {{ $key | upper }}
{{- end }}
{{- end }}
{{- end }}
